### ISSUE TITLE
[Request]: VS2017 Support

### ISSUE THREAD

**Issue by airbreather** [itinero/reminiscence#7]
The projects use the `.xproj` / `project.json` format from the VS2015 preview era, so they can't be used directly with VS2017.  VS2017's auto-upgrade process, however, doesn't seem to understand what you're doing here, and the upgraded project won't build.

My VS2015 is broken at the moment (reinstalling doesn't work), so I can't confirm that I can get it working in that version, but it [looks like](https://github.com/itinero/routing/commit/9cb434e566915d256a55da653a8dd7ba5d88d435) you've set a precedent by upgrading itinero/routing, so I feel OK requesting this.

[Here's](https://gist.github.com/airbreather/3627172b13343f1f0139c5ca51263f2f) the MSBuild detailed output from trying to build the auto-upgraded version, in case that helps you figure this out.

**Comment by xivk** [comment]
Ok, it's on my TODO list, wasn't really urgent because the builds can still be used via nuget and the current state of the project is ok for Itinero.

But nonetheless the projects needs an update, could take more than a week, leaving on holiday.

**Comment by airbreather** [comment]
The reason I bring it up is because I'm seeing Reminiscence stuff show up in a **big** way while measuring what's making edge-based contraction take so long.  I built a routerdb file for planet-170306.osm.pbf, and I thought it might be interesting to see what happens when taking that whole thing and building a contracted graph for it... I just killed the process today, after over two weeks on my really nice gaming computer.  I was using the NoCache profiles because I was getting OutOfMemoryException with the default (even with 64 GiB of physical RAM, a gigantic swap file, and evil tricks).

I was going to see what I can do to make it better.  One thought was to try `System.IO.MemoryMappedFiles` as an alternative implementation of some of the stuff in there.  Ideally, it wouldn't make enough of a difference to justify going much further with it, but I suspect that the OS's native memory management will do **much** better than a slightly naive managed wrapper around a reasonably well-organized managed wrapper around the Win32 I/O APIs.

Another thought was to allocate the gigantic things in unmanaged memory with Marshal.AllocHGlobal and write a thin wrapper around it for managed code to be able to use nicely.

Anyway, I've been able to get what I need for .NET 4.5 locally, of course... if I couldn't even get that far, then my quest would be pretty hopeless.

And of course, in general, I'm probably supposed to restrict the input data to just what's within the geographical area that's relevant to the actual application or query.  Ideally, though, I'd like to get to a place where I could build *one* RouterDb, do *one* contraction (per relevant vehicle profile of course), and leverage that around the world for all the regional solutions.

**Comment by airbreather** [comment]
I'm going to start working on this.  I got my VS2015 working at some point, but it turns out that [`System.Runtime.CompilerServices.Unsafe`](https://www.nuget.org/packages/System.Runtime.CompilerServices.Unsafe/) will not work without C# 7.0 features (it's not just creating methods with by-ref returns, as I had hoped).

**Comment by xivk** [comment]
@airbreather Any ideas on improving this library, that can use a lot of work to be honest are very welcome. There is also this:

http://adamsitnik.com/Span/

I'm preparing work on v2 so it's the right time to make big changes.

**Comment by airbreather** [comment]
The issue in this title was addressed by d308506, so I'm going to close this issue and continue further unrelated discussion on another issue that I'll open shortly.
